image_width: 640
image_height: 480
camera_name: base_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [788.02715,   0.     , 199.69005,
           0.     , 761.15564, 244.95863,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.075254, 0.050957, -0.003077, -0.073244, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [751.26825,   0.     , 173.90137,   0.     ,
           0.     , 794.55969, 243.64831,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
