image_width: 640
image_height: 480
camera_name: innomaker_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [540.17087,   0.     , 322.77125,
           0.     , 541.21713, 270.32487,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.420764, 0.173917, -0.003081, 0.002233, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [447.72339,   0.     , 326.02802,   0.     ,
           0.     , 489.41058, 274.69909,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
