image_width: 640
image_height: 480
camera_name: innomaker_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [549.39994,   0.     , 327.70965,
           0.     , 549.048  , 262.5427 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.419497, 0.158004, 0.000336, 0.000127, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [456.10022,   0.     , 330.78671,   0.     ,
           0.     , 497.75986, 266.87364,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
